server:
  port: 9088
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: customerService
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/customer/**
